<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, '/admbotFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="admin-form theme-success mw1000 center-block" style="padding-bottom: 175px;">

                    <div class="panel heading-border panel-success">  

                        <div class="panel-body bg-light">

                            <div class="section-divider mt20 mb40">
                                <span> Novo Bot </span>
                            </div>                                      
                            <?php
                            echo $this->inputFormulario(KleoForm::traducaoMensagem, $formulario->get(KleoForm::inputMensagem));
                            for ($indice = 1; $indice <= 3; $indice++) {
                                echo $this->inputFormulario(KleoForm::traducaoOpcao . $indice, $formulario->get(KleoForm::inputTitulo . $indice));
                                echo $this->inputFormulario(KleoForm::traducaoResposta . $indice, $formulario->get(KleoForm::inputResposta . $indice));
                            }
                            echo $this->botao('Cadastrar', $this->funcaoOnClick('submeterFormulario(this.form)'));
                            ?>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
echo $this->form()->closeTag();
