<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>Confirmação Nova Campanha</h3>
          </div>
          <div class="panel-body">              
            <?php            
            echo '<pre>';
            echo 'Nome: ' . $this->campanha->getNome();
            echo '<br />Nome: ' . $this->campanha->getNome();
            echo '<br />Data de Envio: ' . $this->campanha->getData_envio()->format('d/m/Y');

            echo '<br />';
            if($this->campanha->getFoto_perfil()){
              echo "Foto de Perfil: ";    
              echo '<img src="assets/'.$this->campanha->getFoto_perfil().'" />';
            }else{
              echo 'Sem Foto de Perfil';
            }
            echo '<br />';
            if($this->campanha->getUpload()){
              echo "Upload: ";     
              echo '<img src="assets/'.$this->campanha->getUpload().'" />';
            }else{
              echo 'Sem Upload';
            }
            echo '<br />';
            if($this->campanha->getMensagem()){
              echo 'Mensagem: ' . $this->campanha->getMensagem();
            }else{
              echo 'Sem Mensagem';
            }
            echo '<br />';
            echo 'Quantidade de Contatos: '.count($this->campanha->getCampanhaListaAtivo()->getLista()->getContatoAtivos());
            echo '</pre>';

            echo '<div>';
            echo $this->botao('Confirmar', $this->funcaoOnClick('kleo("admcampanhaAtivacao", '.$this->campanha->getId().')'));
            echo '</div>';
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>