<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, '/admCampanhaFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>Nova Campanha</h3>
          </div>
          <div class="panel-body">           
            <?php            
            echo $this->inputFormulario(KleoForm::traducaoNomeCampanha, $formulario->get(KleoForm::inputNome));

            echo $this->inputFormulario(KleoForm::traducaoDataEnvio, $formulario->get(KleoForm::inputDataEnvio));

            echo $this->inputFormulario(KleoForm::traducaoFotoPerfil, $formulario->get(KleoForm::inputFotoPerfil), 9);  
            ?>
            <div class="col-md-3">
              <img id="image_upload_preview_fotoPerfil" src="" />
            </div>
            <div class="col-md-12">
              <input type='radio' name='tipo' onclick='mostrarEsconderUpload(0);'> Apenas Texto
              <input type='radio' name='tipo' onclick='mostrarEsconderUpload(1);'> Imagem
              <input type='radio' name='tipo' onclick='mostrarEsconderUpload(2);'> Video
            </div>
            <div id='divUpload' class="hidden">
              <?php
              echo $this->inputFormulario('', $formulario->get(KleoForm::inputUpload));
              ?>
            </div> 
            <div class="col-md-12">
              <img id="image_upload_preview_upload" src="" />
            </div>             
            <?php
            echo $this->inputFormulario(KleoForm::traducaoMensagem, $formulario->get(KleoForm::inputMensagem));              

            echo $this->inputFormulario(KleoForm::traducaoLista, $formulario->get(KleoForm::inputListaId));  

            echo $this->botao('Cadastrar', $this->funcaoOnClick('submeterFormulario(this.form)'));
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<?php
echo $this->form()->closeTag();