<!-- <img src="../../../../../public/img/banner-teste.jpg" class="img-responsive" style="width:100%; height: 200px;"> -->
<?php

use Application\Model\Entity\Situacao;
use Application\Controller\KleoController;

echo $this->cabecalhoPagina('Listagem de Campanhas', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admCampanha", 0);')));
?>  
<div class="content transition animate-panel fadeIn">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">  
                <div class="panel-menu">
                    <input id="fooFilter" type="text" class="form-control" placeholder="Buscar...">                        
                </div>
            </div>
            <div class="panel-body pn">
                <div class="table-responsive">
                    <table class="table footable admin-form theme-warning tc-checkbox-1 fs13 table-hover" data-page-navigation=".pagination" data-page-size="6" data-filter="#fooFilter">
                        <thead>
                            <tr class="bg-light">
                                <?php
                                if ($this->idResponsavel == KleoController::idResponsavelAdmin) {
                                    echo '<th>Empresa</th>';
                                    echo '<th>Responsavel</th>';
                                }
                                ?>                                
                                <th>ID</th>
                                <th>Nome da Campanha</th>
                                <th>Cadastro-Agendamento</th>                                    
                                <th>Status</th>
                                <th>Resumo</th>
                                <td></td> 
                                <td></td> 
                            </tr>
                        </thead>
                        <tbody class="bg-light">
                            <?php
                            if ($this->campanhas) {
                                foreach ($this->campanhas as $campanha) {
                                    echo '<tr>';
                                    echo '<td>' . $campanha->getId() . '</td>';
                                    if ($this->idResponsavel == KleoController::idResponsavelAdmin) {
                                        echo '<td>' . $campanha->getResponsavel()->getNomeEmpresa() . '</td>';
                                        echo '<td>' . $campanha->getResponsavel()->getNome() . '</td>';
                                    }
                                    echo '<td>' . $campanha->getNome() . '</td>';
                                    echo '<td>' . $campanha->getData_envio()->format('d/m/Y') . '</td>';
                                    echo '<td>' . $campanha->getCampanhaSituacaoAtivo()->getSituacao()->getNome();
                                    if ($this->idResponsavel == KleoController::idResponsavelAdmin &&
                                            $campanha->getCampanhaSituacaoAtivo()->getSituacao()->getId() === Situacao::pendente) {
                                        echo $this->botao('Alterar', $this->funcaoOnClick('kleo("admCampanhaSituacao", ' . $campanha->getId() . ')'));
                                    }
                                    echo '</td>';
                                    echo '<td>--/--</td>';
                                    echo '<td></td>';  // '<td><button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-default pull-right ml10">Relatórios</button></td>';
                                    echo '<td></td>';// '<td><button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-default pull-left ml10">Excluir</button></td>';
                                    echo '</tr>';
                                }
                            } else {
                                echo '<tr>';
                                echo '<td colspan="7" class="text-center">' . 'Sem campanhas cadastradas!' . '</td>';
                                echo '</tr>';
                            }
                            ?>                                
                        </tbody>
                        <tfoot class="footer-menu">
                            <tr>
                                <td colspan="12">
                                    <nav class="text-right">
                                        <ul class="pagination hide-if-no-paging"></ul>
                                    </nav>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
