<?php 
use Application\Model\Entity\Situacao;
echo $this->cabecalhoPagina('Listagem de Campanhas', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admCampanha", 0);'))); ?>  
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">         
        <div class="panel-body">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data Envio</th>
                <th>Foto Perfil</th>
                <th></th>
                <th>Upload</th>
                <th></th>
                <th>Mensagem</th>
                <th>Situacao</th>
              </tr>
            </thead>
            <tbody>
              <?php
              if($this->campanhas){
                foreach($this->campanhas as $campanha){
                  echo '<tr>';
                  echo '<td>'.$campanha->getNome(). '</td>';
                  echo '<td>'.$campanha->getData_envio()->format('d/m/Y').'</td>';
                  echo '<td>'.$campanha->getFoto_perfil().'</td>';
                  echo '<td><img src="assets/'.$campanha->getFoto_perfil().'" width="124px" height="124px" /></td>';
                  echo '<td>'.$campanha->getUpload().'</td>';
                  echo '<td><img src="assets/'.$campanha->getUpload().'" width="124px" height="124px"/></td>';
                  echo '<td>'.$campanha->getMensagem().'</td>';
                  echo '<td>'.$campanha->getCampanhaSituacaoAtivo()->getSituacao()->getNome();
                  if($campanha->getCampanhaSituacaoAtivo()->getSituacao()->getId() === Situacao::pendente){                  
                    echo $this->botao('Alterar', $this->funcaoOnClick('kleo("admCampanhaSituacao", '.$campanha->getId().')'));
                  }
                  echo  '</td>';
                  echo '</tr>'; 
                }
              }else{
                echo '<tr>';
                echo '<td colspan="4" class="text-center">'.'Sem campanhas cadastradas!'.'</td>';
                echo '</tr>'; 
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>