<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'admCampanhaSituacaoFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<div class="register-container">
  <div class="row">
    <div class="col-md-12">
      <div class="hpanel">
        <div class="panel-body">
          <div class='text-center'>
            <h3>Alterar Situacao</h3>
          </div>
          <div class='well'>
            <p>Nome: <?php echo $this->campanha->getNome(); ?></p>
            <p>Data de Envio: <?php echo $this->campanha->getData_envio()->format('d/m/Y'); ?></p>
            <p>Foto de Perfil: <?php echo $this->campanha->getFoto_perfil(); ?></p>
            <p><img src="assets/<?php echo $campanha->getFoto_perfil(); ?>" width="124px" height="124px" /></p>
            <p>Upload: <?php echo $this->campanha->getUpload(); ?></p>
            <p><img src="assets/<?php echo $campanha->getUpload(); ?>" width="124px" height="124px" /></p>
            <p>Mensagem: <?php echo $this->campanha->getMensagem(); ?></p>
          </div>
          <?php
          echo $this->inputFormulario(KleoForm::traducaoSituacao, $formulario->get(KleoForm::inputSituacao));
          ?>
          <div class="text-center">
            <?php echo $this->botao('Atualizar', $this->funcaoOnClickSubmeterFormulario()); ?>
            <?php echo $this->botao('Voltar', $this->funcaoOnClick('mudarPaginaComLoader("/admCampanhas")'), 2); ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
echo $this->form()->closeTag();