<?php 
use Application\Model\Entity\Situacao;
echo $this->cabecalhoPagina('Listagem de Responsaveis'); ?> 
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">          
        <div class="panel-body">
          <table id="tabelaEmpresasParaAnalise" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Empresa</th>
                <th>Responsavel</th>
                <th>Saldo</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <?php
              foreach($this->responsaveis as $responsavel){
                if($responsavel->getId() !== 1){
                  echo '<tr>';
                  echo '<td>'.$responsavel->getNomeEmpresa().'</td>';
                  echo '<td>'.$responsavel->getNome().'</td>';
                  echo '<td>'.number_format($responsavel->getSaldo(), 0, '.','.').'</td>';                  
                  echo '<td>';             
                  echo $this->botao('Extrato', $this->funcaoOnClick('kleo("admExtrato", '.$responsavel->getId().')'));
                  echo '</td>';
                  echo '</tr>';
                }
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaEmpresasParaAnalise').dataTable();
  }
</script>