<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Compra de Crêdito</h3>
                    </div>
                    <div class="panel-body">              
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan bottom-pad-small wow fadeInUp">
                                    <h3>Básico<strong> I</strong> <small>5.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,091<small>/R$455,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","1")')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan bottom-pad-small special wow fadeInUp">
                                    <h3>Básico<strong> II</strong> <small>10.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,089<small>/R$890,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","2")')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan wow fadeInUp">
                                    <h3>Básico<strong> III</strong> <small>30.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,085<small>/R$2.550,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","3")')); ?>
                                </div>
                            </div>


                        </div>
                        <br />
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan bottom-pad-small wow fadeInUp">
                                    <h3>Intermediário<strong> I</strong> <small>50.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,065<small>/R$3.250,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","4")')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan bottom-pad-small special wow fadeInUp">
                                    <h3>Intermediário<strong> II</strong> <small>100.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,055<small>/R$5.500,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","5")')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4 col-md-4">
                                <div class="pricing_plan wow fadeInUp">
                                    <h3>Intermediário<strong> III</strong> <small>300.000 créditos</small></h3>
                                    <div class="the_price"><span>R$</span>0,042<small>/R$12.600,00</small></div>
                                    <?php echo $this->botao('Contrate', $this->funcaoOnClick('kleo("admSolicitarCredito","6")')); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>