<?php
echo $this->cabecalhoPagina('Extrato', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admTransferencia", '.$responsavel->getId().')'))); 
?>  
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">         
        <div class="panel-body">
          <h3>
            <?php echo $responsavel->getNomeEmpresa(); ?> - 
            <?php echo $responsavel->getNome(); ?> - 
            <?php echo number_format($responsavel->getSaldo(),0,'.','.'); ?> Créditos
          </h3>
          <table id="tabelaContaCorrente" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Valor</th>
                <th>Preço</th>
                <th>Tipo</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <?php  
              if($responsavel->getContaCorrente()){
                foreach($responsavel->getContaCorrente() as $contaCorrente){
                  echo '<tr>';
                  echo '<td>'.$contaCorrente->getValor().'</td>';
                  echo '<td>'.$contaCorrente->getPreco().'</td>';
                  echo '<td>'; 
                  if($contaCorrente->getCredito() === 'S'){
                    echo 'Crédito';
                  }else{
                    echo 'Débito';
                  }
                  echo '</td>';
                  echo '</tr>';
                }
              }            
              ?>                             
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>