<?php 
use Application\Model\Entity\Situacao;
echo $this->cabecalhoPagina('Lista de Contatos', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admlista", 0);'))); ?>  
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">         
        <div class="panel-body">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Descri&ccedil;&atilde;o</th>
                <th>Contatos</th>
                <th>Zap</th>
              </tr>
            </thead>
            <tbody>
              <?php
              if($this->listas){
                foreach($this->listas as $lista){
                  echo '<tr>';
                  echo '<td>' .$lista->getNome(). '</td>';
                  echo '<td>' .$lista->getDescricao(). '</td>';
                  echo '<td></td>';
                  echo '<td></td>';
                  echo '</tr>'; 
                }
              }else{
                echo '<tr>';
                echo '<td colspan="6" class="text-center">'.'Sem listas cadastradas!'.'</td>';
                echo '</tr>'; 
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>