<?php

use Application\Model\Entity\Situacao;
use Application\Controller\KleoController;

echo $this->cabecalhoPagina('Lista de Contatos', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admlista", 0);')));
?>  
<div class="content transition animate-panel fadeIn">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-menu">   
                    <input id="fooFilter" type="text" class="form-control" placeholder="Buscar...">
                </div>                     
            </div>
            <div class="panel-body pn">
                <div class="table-responsive">
                    <table class="table footable admin-form theme-warning tc-checkbox-1 fs13 table-hover" data-page-navigation=".pagination" data-page-size="6" data-filter="#fooFilter">
                        <thead>
                            <tr class="bg-light">
                                <th>ID</th>
                                <?php
                                if ($this->idResponsavel == KleoController::idResponsavelAdmin) {
                                    echo '<th>Empresa</th>';
                                    echo '<th>Responsavel</th>';
                                }
                                ?>
                                <th>Lista</th>
                                <th>Descri&ccedil;&atilde;o</th>
                                <th>Contatos</th>
                                <th>Zap</th>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->listas) {
                                foreach ($this->listas as $lista) {
                                    echo '<tr>';
                                    echo '<td>' . $lista->getId() . '</td>';
                                    if ($this->idResponsavel == KleoController::idResponsavelAdmin) {
                                        echo '<td>' . $lista->getResponsavel()->getNomeEmpresa() . '</td>';
                                        echo '<td>' . $lista->getResponsavel()->getNome() . '</td>';
                                    }
                                    echo '<td>' . $lista->getNome() . '</td>';
                                    echo '<td>' . $lista->getDescricao() . '</td>';
                                    echo '<td>' . count($lista->getContatoAtivos()) . '</td>';
                                    echo '<td>--/--</td>';
                                    echo '<td>';
                                    echo $this->botao('Excluir', $this->funcaoOnClick('validarExclusao("admlistaexcluir", ' . $lista->getId() . ')'), 2);
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            } else {
                                echo '<tr>';
                                echo '<td colspan="7" class="text-center">' . 'Sem listas cadastradas!' . '</td>';
                                echo '</tr>';
                            }
                            ?>                                
                        </tbody>
                        <tfoot class="footer-menu">
                            <tr>
                                <td colspan="12">
                                    <nav class="text-right">
                                        <ul class="pagination hide-if-no-paging"></ul>
                                    </nav>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>