<?php 

use Application\Model\Entity\Situacao;
use Application\Controller\KleoController;

echo $this->cabecalhoPagina('Lista de Contatos', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("admlista", 0);'))); ?>  
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">         
        <div class="panel-body">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <?php
                if($this->idResponsavel == KleoController::idResponsavelAdmin){
                  echo '<th>Empresa</th>';
                  echo '<th>Responsavel</th>';                  
                }
                ?>
                <th>Lista</th>
                <th>Descri&ccedil;&atilde;o</th>
                <th>Contatos</th>
                <th>Zap</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <?php
              if($this->listas){
                foreach($this->listas as $lista){
                  echo '<tr>';
                  if($this->idResponsavel == KleoController::idResponsavelAdmin){
                    echo '<td>'. $lista->getResponsavel()->getNomeEmpresa() . '</td>';
                    echo '<td>'. $lista->getResponsavel()->getNome() . '</td>';
                  }
                  echo '<td>' . $lista->getNome() . '</td>';
                  echo '<td>' . $lista->getDescricao() . '</td>';
                  echo '<td>' . count($lista->getContato()) . '</td>';
                  echo '<td>' . count($lista->getContatoComZap()) . '</td>';
                  echo '<td>';
                  echo $this->botao('Excluir', $this->funcaoOnClick('validarExclusao("admlistaexcluir", '.$lista->getId().')'));
                  echo '</td>';
                  echo '</tr>'; 
                }
              }else{
                echo '<tr>';
                echo '<td colspan="6" class="text-center">'.'Sem listas cadastradas!'.'</td>';
                echo '</tr>'; 
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>