<?php

use Application\Model\Entity\Situacao;

echo $this->cabecalhoPagina('Listagem de Responsaveis');
?> 
<div class="content transition animate-panel fadeIn">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">  
                <div class="panel-menu">
                    <input id="fooFilter" type="text" class="form-control" placeholder="Buscar...">                        
                </div>
            </div>
            <div class="panel-body pn">
                <div class="table-responsive">
                    <table class="table footable admin-form theme-warning tc-checkbox-1 fs13 table-hover" data-page-navigation=".pagination" data-page-size="6" data-filter="#fooFilter">
                        <thead>
                            <tr class="bg-light">
                                <th>Data</th>
                                <th>Empresa</th>
                                <th>Responsavel</th>
                                <th>Contato</th>
                                <th>Situação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->responsaveis as $responsavel) {
                                if ($responsavel->getId() !== 1) {
                                    echo '<tr>';
                                    echo '<td>' . $responsavel->getData_criacaoFormatada() . '</td>';
                                    echo '<td>' . $responsavel->getNomeEmpresa() . '</td>';
                                    echo '<td>' . $responsavel->getNome() . '</td>';
                                    echo '<td>' . $responsavel->getTelefone() . '</td>';
                                    echo '<td>' . $responsavel->getResponsavelSituacaoAtivo()->getSituacao()->getNome();
                                    if ($responsavel->getResponsavelSituacaoAtivo()->getSituacao()->getId() === Situacao::primeiroContato) {
                                        echo $this->botao('Alterar', $this->funcaoOnClick('kleo("admResponsavelSituacao", ' . $responsavel->getId() . ')'));
                                    }
                                    echo $this->botao('Ver', $this->funcaoOnClick('kleo("admResponsavelVer", ' . $responsavel->getId() . ')'));
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            }
                            ?>                                
                        </tbody>
                        <tfoot class="footer-menu">
                            <tr>
                                <td colspan="12">
                                    <nav class="text-right">
                                        <ul class="pagination hide-if-no-paging"></ul>
                                    </nav>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.onload = initPage;

    function initPage() {
        $('#tabelaEmpresasParaAnalise').dataTable();
    }
</script>