<!-- MAIN CONTENT SECTION -->
<div id="wrapper">
  <div class="content transition animate-panel fadeIn">
    <div class="row">
      <div class="col-lg-offset-4 col-lg-4">
        <div class="hpanel hgreen">
          <div class="panel-body">
            <h3><?php echo $responsavel->getNome(); ?></h3>
            <p><?php echo $responsavel->getTelefone(); ?></p>
            <p><?php echo $responsavel->getEmail(); ?></p>
            <div class="text-muted font-bold m-b-xs">Empresa</div>
            <h3><?php echo $responsavel->getNomeEmpresa(); ?></h3>
            <h3><?php echo $responsavel->getCNPJ(); ?></h3>
          </div>
          <div class="panel-footer contact-footer">
            <div class="row"> 
              <?php echo $this->botao('Voltar', $this->funcaoOnClick('mudarPaginaComLoader("/admResponsaveis")'), 2);?>
            </div>
          </div>
        </div>  
      </div>   
    </div>
  </div>
</div>