<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Transferência</h3>
                    </div>
                    <div class="panel-body">                       
                        <p>DIEGO ALLAN KORT - ME</p>
                        <p>CNPJ 027.613.715/0001-76: </p>
                        <p>Ag: 0484</p>
                        <p>C/C: 8542-1</p>
                        <p>BANCO BRADESCO</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>