<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, '/admTransferenciaFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">  
        <div class="panel-heading">
          <h3>Nova Transferência - <?php echo $this->responsavel->getNome(); ?></h3>            
        </div>
        <div class="panel-body">
          <?php 
          echo $this->inputFormulario(KleoForm::traducaoValor, $formulario->get(KleoForm::inputValor), 3);
          echo $this->inputFormulario(KleoForm::traducaoPreco, $formulario->get(KleoForm::inputPreco), 3);
          echo $this->inputFormulario(KleoForm::traducaoCredito, $formulario->get(KleoForm::inputCredito), 3);  
          ?>
          <div class="form-group col-md-3 col-lg-3">
            <?php echo $this->botao('Cadastrar', $this->funcaoOnClick('submeterFormulario(this.form)')); ?> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
echo $this->form()->closeTag();