<?php

use Application\Controller\KleoController;

echo $this->doctype();
$versao = '?v=1.2.4';
?>
<html lang="pt-BR">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <!-- Title Head -->
    <?php
    $NAME_APPLICATION = $this->translate(KleoController::nomeAplicacao);
    echo $this
      ->headTitle($NAME_APPLICATION)
      ->setSeparator(' - ')
      ->setAutoEscape(false)
      ;
    ?>

    <!-- Meta Head -->
    <?php
    echo $this
      ->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendName('theme-color', '#3498db')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ;
    ?>

    <!-- Styles -->
    <?php
    echo $this
      ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpeg'))
      ->prependStylesheet($this->basePath() . '/css/splash.css' . $versao)
      ->prependStylesheet($this->basePath() . '/vendor/plugins/ladda/ladda.min.css')
      ->prependStylesheet($this->basePath() . '/vendor/plugins/footable/css/footable.core.min.css')
      ->prependStylesheet($this->basePath() . '/vendor/plugins/animate/animate.min.css')
      ->prependStylesheet($this->basePath() . '/assets/admin-forms.min.css')
      ->prependStylesheet($this->basePath() . '/assets/skin/default_skin/css/theme.min.css')
      ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
      ;
    ?>       
  </head>
  <body class="external-page external-alt sb-l-c sb-r-c">
    <?php echo $this->splash(); ?>
    <!-- Start: Main -->
    <div id="main">
      <?php
      if ($this->mostrarMenu !== 0) {
        echo $this->menu();
      }
      ?> 
      <section id="content_wrapper" style="margin-top: 50px;">
        <div id="content">
          <?php echo $this->content; ?>
        </div>
      </section>
    </div>
    <!-- End: Main -->

    <!-- BEGIN: PAGE SCRIPTS -->
    <?php
    echo $this
      ->headScript()
      ->prependFile($this->basePath() . '/js/validacoes.js' . $versao)
      ->prependFile($this->basePath() . '/js/funcoes.js' . $versao)
      ->prependFile($this->basePath() . '/assets/js/main.js')
      ->prependFile($this->basePath() . '/assets/js/utility/utility.js')
      ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.filter.min.js')
      ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.all.min.js')
      ->prependFile($this->basePath() . '/vendor/plugins/ladda/ladda.min.js')
      ->prependFile($this->basePath() . '/vendor/jquery/jquery_ui/jquery-ui.min.js')
      ->prependFile($this->basePath() . '/vendor/jquery/jquery-1.11.1.min.js')
      ;
    echo $this->inlineScript();
    ?>
    <script type="text/javascript">

      jQuery(document).ready(function () {

        "use strict";

        // Init Theme Core
        Core.init();

        // Init Ladda Plugin on buttons
        Ladda.bind('.ladda-button', {
          timeout: 500
        });

        $('.footable').footable();

      });

      $(window).bind("load", function () {
        // Remove splash screen after load
        $('.splash').css('display', 'none');

        var url = window.location.href;
        var splitUrl = url.split('/');
        if (splitUrl[3].includes('pub')
            || splitUrl[3].includes('adm')) {
          $('body')
            .removeClass('external-page')
            .removeClass('external-alt');
        }
        if (splitUrl[3].includes('adm')) {
          $('body')
            .removeClass('sb-l-c');
        }
      });
    </script>
    <!-- END: PAGE SCRIPTS -->
  </body>
</html>
