<!-- 
@Autor Ivan Tavares
-->
<div class="center-block mt70" style="max-width: 625px">

    <!-- Login Logo + Meta -->
    <div class="row table-layout">        
        <a href="/"><img src="../../../../../public/img/site/logo_zapmarketing_painel3.png" class="embed-responsive-item center-block"></a>
    </div>
    <!-- Confirmation Panel -->
    <div class="panel mt15">
        <div class="panel-body pt30 p25 pb15">           
            <h2 class="text-dark mbn confirmation-header text-center"><i class="fa fa-check text-success"></i>Senha cadastrada com sucesso!</h2>            
            <p class="text-right mt20"><button class="btn btn-success btn-rounded ph40 center-block" type="button" onclick="location.href = '/login'">Acesse o painel</button></p>          
        </div>
    </div>

</div>