<!-- 
@Autor Ivan Tavares
-->
<div class="center-block mt70" style="max-width: 625px">

  <!-- Login Logo + Meta -->
  <div class="row table-layout">

    <div class="col-xs-12 pln">
      <h2 class="text-dark mbn confirmation-header"><i class="fa fa-check text-success"></i>Email enviado com sucesso!</h2>
    </div>

    <div class="col-xs-5 text-right va-b">
      <div class="meta-links alt">
        <a href="#" class="">Zapmarketing.com</a>                        
      </div>
    </div>

  </div>

  <!-- Confirmation Panel -->
  <div class="panel mt15">
    <div class="panel-body pt30 p25 pb15">          


      <p class="lh25 text-muted fs15">Em breve entraremos em contato. </p>

      <p class="text-right mt20"><button class="btn btn-primary btn-rounded ph40" type="button" onclick="location.href='/'">Voltar</button></p>

    </div>
  </div>

</div>